import React from 'react';
import { Shield, Lock, AlertTriangle, Info } from 'lucide-react';

const AboutPage = () => {
  return (
    <div className="bg-slate-50 min-h-screen py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="text-center mb-12">
          <h1 className="text-4xl font-extrabold text-slate-900 mb-4">About SafeSkin AI</h1>
          <p className="text-lg text-slate-600">
            An educational and AI research project exploring image-based skin condition screening.
          </p>
        </div>

        <div className="space-y-8">
          
          {/* Medical Disclaimer */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 flex gap-4">
            <AlertTriangle className="w-8 h-8 text-amber-600 shrink-0" />
            <div>
              <h2 className="text-xl font-bold text-amber-900 mb-2">Important Medical Disclaimer</h2>
              <p className="text-amber-800 leading-relaxed">
                SafeSkin AI is an experimental AI screening tool. It does <strong>not</strong> provide medical diagnoses. 
                The results generated by this system should not replace professional medical advice, diagnosis, or treatment. 
                Always consult a qualified healthcare provider with any questions you may have regarding a medical condition.
              </p>
            </div>
          </div>

          <div className="bg-white rounded-2xl p-8 border border-slate-100 shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <Info className="w-6 h-6 text-sky-600" />
              <h2 className="text-2xl font-bold text-slate-900">Project Objective</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              The goal of SafeSkin AI is to develop an intelligent, confidence-aware skin condition screening system. 
              Unlike traditional models that force a prediction regardless of confidence, our architecture prioritizes 
              reducing false positives. If the AI is uncertain, it will explicitly state so rather than incorrectly 
              classifying healthy skin as diseased.
            </p>
          </div>

          <div className="bg-white rounded-2xl p-8 border border-slate-100 shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-6 h-6 text-indigo-600" />
              <h2 className="text-2xl font-bold text-slate-900">Responsible AI & Limitations</h2>
            </div>
            <p className="text-slate-600 leading-relaxed mb-4">
              AI models are only as good as the data they are trained on. Known limitations of this system include:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-slate-600">
              <li><strong>Lighting & Camera Quality:</strong> Poor lighting or blurry images significantly reduce accuracy.</li>
              <li><strong>Skin Tone Variations:</strong> While efforts are made to ensure diverse training data, performance may vary across different skin tones.</li>
              <li><strong>Rare Conditions:</strong> The system is currently only trained to recognize a specific subset of common conditions.</li>
              <li><strong>Contextual Lack:</strong> AI analyzes pixels, not patient history, symptoms, or tactile feedback (how the skin feels).</li>
            </ul>
          </div>

          <div className="bg-white rounded-2xl p-8 border border-slate-100 shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <Lock className="w-6 h-6 text-emerald-600" />
              <h2 className="text-2xl font-bold text-slate-900">Privacy & Security</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Because skin images may contain sensitive health-related information, this application employs:
            </p>
            <ul className="list-disc pl-5 mt-4 space-y-2 text-slate-600">
              <li>Secure Authentication & Row Level Security (RLS)</li>
              <li>Private Storage Buckets (No public image URLs)</li>
              <li>Complete Data Deletion Capabilities (You can delete your images and history at any time)</li>
              <li>Minimal Data Collection practices</li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  );
};

export default AboutPage;
