-- =============================================================================
-- SafeSkin AI – Supabase Storage Configuration
-- Migration: 002_storage.sql
-- Description: Creates private storage buckets for user skin images and
--              GradCAM heat-map results. Applies RLS-style Storage policies
--              so that each user can only access files under their own
--              user-id prefix in the path.
-- Run Order: 2nd (after 001_initial_schema.sql)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- IMPORTANT NOTE ON STORAGE POLICIES
-- ---------------------------------------------------------------------------
-- Supabase Storage object paths are structured as:
--   <bucket_name>/<user_id>/<sub-folder>/<filename>
--
-- The helper function storage.foldername(name) returns an array of path
-- segments. Index [1] (1-based) is the first segment after the bucket name,
-- which we enforce to equal the calling user's UUID.
-- ---------------------------------------------------------------------------

-- =============================================================================
-- 1. BUCKET: skin-images
--    Stores original skin photos uploaded by users before AI analysis.
--    Access is PRIVATE – no anonymous reads.
-- =============================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'skin-images',          -- Bucket ID (must match bucket name for simplicity)
    'skin-images',          -- Human-readable name shown in dashboard
    false,                  -- private: NOT publicly accessible
    10485760,               -- 10 MB max file size (skin photos rarely exceed this)
    ARRAY[
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp',
        'image/heic',
        'image/heif'
    ]
)
ON CONFLICT (id) DO NOTHING;  -- Idempotent: safe to re-run if bucket already exists

COMMENT ON TABLE storage.buckets IS
    'skin-images: private bucket for original user-uploaded skin photos.';

-- =============================================================================
-- 2. BUCKET: gradcam-results
--    Stores GradCAM heat-map overlay images generated by the AI backend.
--    Access is PRIVATE – files are served via signed URLs with short TTL.
-- =============================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'gradcam-results',
    'gradcam-results',
    false,                  -- private: served via signed URLs only
    5242880,                -- 5 MB max (GradCAM outputs are typically small PNGs)
    ARRAY[
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp'
    ]
)
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 3. STORAGE RLS POLICIES – skin-images bucket
-- =============================================================================
-- File path convention inside the bucket:
--   <user_uuid>/screenings/<screening_uuid>.<ext>   -- original screening images
--   <user_uuid>/progress/<progress_uuid>.<ext>      -- progress tracking images
--
-- storage.foldername(name)[1] extracts the first path segment (the user UUID).
-- =============================================================================

-- Allow authenticated users to SELECT (read) their own objects
CREATE POLICY "skin_images_select_own"
    ON storage.objects FOR SELECT
    TO authenticated
    USING (
        bucket_id = 'skin-images'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- Allow authenticated users to INSERT (upload) objects under their own prefix
CREATE POLICY "skin_images_insert_own"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (
        bucket_id = 'skin-images'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- Allow authenticated users to UPDATE metadata on their own objects
CREATE POLICY "skin_images_update_own"
    ON storage.objects FOR UPDATE
    TO authenticated
    USING (
        bucket_id = 'skin-images'
        AND storage.foldername(name)[1] = auth.uid()::text
    )
    WITH CHECK (
        bucket_id = 'skin-images'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- Allow authenticated users to DELETE their own objects
CREATE POLICY "skin_images_delete_own"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (
        bucket_id = 'skin-images'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- =============================================================================
-- 4. STORAGE RLS POLICIES – gradcam-results bucket
-- =============================================================================
-- File path convention:
--   <user_uuid>/gradcam/<screening_uuid>_heatmap.png
--
-- The backend service role inserts GradCAM files (bypasses RLS by using the
-- service role key). Users can only read/delete their own heat-maps.
-- =============================================================================

-- Users can read their own GradCAM overlays (fetched via signed URL)
CREATE POLICY "gradcam_select_own"
    ON storage.objects FOR SELECT
    TO authenticated
    USING (
        bucket_id = 'gradcam-results'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- Service role writes GradCAM images on behalf of users.
-- This INSERT policy covers cases where the frontend uploads directly
-- (e.g., if the architecture changes to a direct-upload model).
CREATE POLICY "gradcam_insert_own"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (
        bucket_id = 'gradcam-results'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- Users can delete their own GradCAM overlays
CREATE POLICY "gradcam_delete_own"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (
        bucket_id = 'gradcam-results'
        AND storage.foldername(name)[1] = auth.uid()::text
    );

-- =============================================================================
-- 5. CORS CONFIGURATION (informational – set via Supabase Dashboard)
-- =============================================================================
-- Supabase Storage CORS is configured in the Dashboard under
-- Storage > Settings > CORS. Recommended origins for development:
--   - http://localhost:5173   (Vite web dev server)
--   - http://localhost:3000   (alternative web port)
-- For production add the deployed domain.
-- =============================================================================

-- =============================================================================
-- END OF MIGRATION 002
-- =============================================================================
